= tblite-run(1)
Sebastian Ehlert (@awvwgk)
:doctype: manpage

== Name
tblite-run - Run tight-binding calculations

== Synopsis
*tblite run* [_options_] _input_


== Description

Evaluates the tight-binding model on the provided input structure.
Periodic calculations are performed automatically for periodic input formats.
Reads .CHRG and .UHF files if present in the same directory as the input.

Supported geometry input formats are:

- Xmol/xyz files (xyz, log)
- Turbomole's coord, riper's periodic coord (tmol, coord)
- DFTB+ genFormat geometry inputs as cluster, supercell or fractional (gen)
- VASP's POSCAR/CONTCAR input files (vasp, poscar, contcar)
- Protein Database files, only single files (pdb)
- Connection table files, molfile (mol) and structure data format (sdf)
- Gaussian's external program input (ein)


== Options

*-c, --charge* _integer_::
     Set charge to molecule,
     overrides charge in .CHRG file

*--spin* _integer_::
     Set number of unpaired electrons for molecule,
     overrides spin in .UHF file

*--method* _string_::
     Name of the parametrisation to use, supported are
     _gfn1_, _ipea1_ and _gfn2_ (default).

*--param* _string_::
     Read tight binding parametrization from _string_.

*--etemp* _real_::
     Electronic temperature for calculation in Kelvin (default: 300K).

*--guess* _string_::
     Guess for the initial populations, possible options:
     _sad_ (default), and _eeq_.

*--efield* _real_,_real_,_real_::
     Homogeneous electric field in V/Å, takes three comma separated real values.

*--alpb* _real_|_string_::
     Use analytical linearized Poisson-Boltzmann solvation model.
     Solvent is specified by dielectric constant or solvent name.
     **Important**: This feature is not stable and results are subject to change.

*--gbsa* _real_|_string_::
     Use generalized Born solvation model.
     Solvent is specified by dielectric constant or solvent name.
     **Important**: This feature is not stable and results are subject to change.

*--cpcm* _real_|_string_::
     Use conductor-like polarizable continuum solvation model.
     Solvent is specified by dielectric constant or solvent name.
     **Important**: This feature is not stable and results are subject to change.

*--spin-polarized*::
     Use spin-polarized Hamiltonian with colinear spins.
     **Important**: This feature is not stable and results are subject to change.

*--acc* _real_::
     Accuracy of the calculation,
     lower values set tighter convergence criteria.

*--iterations* _int_::
     Number of iterations for converging the electronic structure.
     Default: 250.

*--solver* _name_::
     Electronic solver for SCF, possible options:
     _gvd_ (default), and _gvr_

*--grad* [_file_]::
     Evaluates analytical gradient,
     results are stored in _file_ (default: tblite.txt)

*--json* [_file_]::
     Dump results as JSON output to _file_ (default: tblite.json)

*-i, --input* _format_::
     Hint for the format of the input file

*-v, --verbose*::
     Increase verbosity of printout

*-s, --silent*::
     Reduce verbosity of printout

*--version*::
     Prints version number and citation

*--help*::
     Show this message


Command line arguments can be read from an indirect file / response file by specifying the file with @_name_ in the command line.
Each line in the file is interpreted as command line argument, shell like escape sequences are not available.
The file can contain further @_name_ inputs. If the file cannot be the argument is used literally.


== See also

*tblite*(1)
