fixes:
  - "/home/runner/work/tblite/tblite::"
  - "tblite/::python/tblite/"

# Exclude tests, dependencies, and non-source directories
ignore:
  - "assets/"
  - "build/"
  - "config/"
  - "doc/"
  - "include/"
  - "man/"
  - "subprojects/"
  - "test/"
  - "**/test_*.py"

