fixes:
  - "/home/runner/work/tblite/tblite::"
  - "tblite/::python/tblite/"

# Only cover core library (`app` and `src` directories)
ignore:
  - "assets/"
  - "build/"
  - "config/"
  - "doc/"
  - "include/"
  - "man/"
  - "subprojects/"
  - "test/"
  - "**/test_*.py"

