set(CMAKE_IMPORT_FILE_VERSION 1)

set(
  TBLITE_INCLUDEDIRS
  "@CMAKE_INSTALL_PREFIX@/@CMAKE_INSTALL_INCLUDEDIR@"
  "@CMAKE_INSTALL_PREFIX@/@CMAKE_INSTALL_INCLUDEDIR@/@module-dir@"
)
find_library(
  TBLITE_LIBRARIES
  "@PROJECT_NAME@"
  PATHS "@CMAKE_INSTALL_PREFIX@/@CMAKE_INSTALL_LIBDIR@"
  NO_DEFAULT_PATH
)
set(
  TBLITE_DEPENDENCIES
  "$<$<BOOL:${TBLITE_USE_MCTCLIB}>:mctc-lib::mctc-lib>"
  "$<$<BOOL:${TBLITE_USE_MULTICHARGE}>:multicharge::multicharge>"
  "$<$<BOOL:${TBLITE_USE_TOMLF}>:toml-f::toml-f>"
  "$<$<BOOL:${TBLITE_USE_DFTD4}>:dftd4::dftd4>"
  "$<$<BOOL:${TBLITE_USE_SDFTD3}>:s-dftd3::s-dftd3>"
  "$<$<BOOL:${TBLITE_USE_DDX}>:ddx::ddx>"
  "$<$<BOOL:${TBLITE_WITH_OpenMP}>:OpenMP::OpenMP_Fortran>"
  "$<$<BOOL:${TBLITE_WITH_HDF5}>:HDF5::HDF5>"
  "$<$<BOOL:${TBLITE_WITH_TREXIO}>:TREXIO::TREXIO>"
  "LAPACK::LAPACK"
)

add_library(@PROJECT_NAME@::@PROJECT_NAME@-lib INTERFACE IMPORTED)
add_library(@PROJECT_NAME@::@PROJECT_NAME@ ALIAS @PROJECT_NAME@::@PROJECT_NAME@-lib)
target_link_libraries(@PROJECT_NAME@::@PROJECT_NAME@-lib INTERFACE ${TBLITE_LIBRARIES} ${TBLITE_DEPENDENCIES})
target_include_directories(@PROJECT_NAME@::@PROJECT_NAME@-lib INTERFACE ${TBLITE_INCLUDEDIRS})
