[build-system]
requires = ["mesonpep517"]
build-backend = "mesonpep517.buildapi"

[tool.mesonpep517.metadata]
author = "Sebastian Ehlert"
author-email = "awvwgk@disroot.org"
summary = "Light-weight tight-binding framework"
description-file = "README.rst"
home-page = "https://tblite.readthedocs.io"
requires = [
   "cffi",
   "numpy",
]
requires-python = ">=3.6"
